### PR TITLE
Feature/matrix helper remove

### PR DESCRIPTION
**Pull request by pratikdhandharia**
DISTR-917 Removing the Matrix Helper package. 

@shreya2k7 @afard @jorgemarsal @etduwx @fun-indra Please review.

### CODE REVIEW

**Comment by jorgemarsal** [comment]
Looks good to me.

**Comment by afard** [comment]
The changes on the algorithm packagess also looks fine.

**Comment by shreya2k7** [comment]
Looks good. Pls make sure to archive matrix helper package to Stash under algorithm/ folder.

Thanks,
Shreya

**Comment by pratikdhandharia** [comment]
@shreya2k7 I have created another pull request under Stash to archive the MatrixHelper package already. Please review there as well.

**Comment by shreya2k7** [comment]
It looks good as well.

**Pull request merged**
