### PR TITLE
Feature/cran installer

### PR DESCRIPTION
**Pull request by jorgemarsal**
This is the first step to make DR installable from CRAN or Github:
I've done a couple things:
1. Move all the c++ under platform/master/src
2. Do not use SSH to start local workers.
3. Remove references to boost and common/ from matrix_helper and executor packages. Not they're only 3MB each.
4. Store the binaries (R-executor-bin, R-worker-bin ...) and cluster_conf.xml in the package itself instead of /opt/

One thing I haven't tested is the RPM/DEB generation and the CI (regression tests, etc.). Hopefully Shreya and Rich can help with that.

The steps to test this PR are (in Centos 7):

    sudo yum install gcc-c++ git libxml2-devel bison byacc flex epel-release
    sudo yum install R

    git clone https://github.com/vertica/DistributedR.git
    cd DistributedR/
    git fetch
    git checkout feature/cran-installer

    cd platform/
    sudo R CMD INSTALL master/src/third_party/Rcpp_0.11.6.tar.gz 
    sudo R CMD INSTALL master/src/third_party/RInside_0.2.13.tar.gz 
    sudo R CMD INSTALL master/src/third_party/XML_3.98-1.1.tar.gz 

    sudo R CMD INSTALL master/
    sudo R CMD INSTALL executor/
    sudo R CMD INSTALL matrix_helper/

    R -e "library(distributedR); distributedR_start()"

### CODE REVIEW

**Comment by VinXu123** [comment]
@shreya2k7 @pratikdhandharia @zeliff @afard Please review and comment

**Comment by shreya2k7** [comment]
Hi Jorge,

A couple of comments:
1. The description is very nice to get started and install but it would be great if you could put short summary about the changes that affect the developers as well. Like where build.mk, vars.mk and Makefile were moved to. I tried to scan through but there are 146 changed files and one can get lost. This can go here or in a confluence page.

2. Earlier, developers used to clear the build area (for a fresh build) using make clean/make distclean. Also there was a target to run unit tests make test_platform. There we also some useful targets to build docs and algorithms. How can we run those now?

3. Executor package should marked as a dependency for DistributedR package because its functions wont run without the Executor package. Executor should be installed before DistributedR package.

4. Should we rename the package names?

5. When I am trying to build on a CentOS 6 machine, it complaining with error:
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/usr/lib64/R/library/distributedR/libs/distributedR.so':
  /usr/lib64/R/library/distributedR/libs/distributedR.so: undefined symbol: _ZN6presto5Array14_default_name_E

Couple of comments in the code.

**Comment by pratikdhandharia** [comment]
I think we need to the dependency list in the ReadME file.

**Comment by jorgemarsal** [comment]
Thanks for the comments Shreya.

1. Added more in the first comment.
2. See first comment also.
3. Added `Executor` and `MatrixHelper` as dependencies. We can remove `MatrixHelper` if we get rid of it finally.
4. Not sure, people can propose names.
5. I built from a fresh Centos 6 docker image and didn't see that. Maybe try cleaning the build ...
6. Those dirs don't even exist in the `feature/cran-installer` branch. Maybe they're from a previous build?
7. Not having source files under `master/src` might be a problem. In any case this is the way it was before.
8. Removed it.
9. bin/ has some scripts. install/ is not there in my build, maybe it's from a previous build?

**Comment by jorgemarsal** [comment]
Thanks Pratik. I've updated the README.

**Comment by jorgemarsal** [comment]
@etduwx There are some changes in the Zipkin stuff. We don't compile in the same way so now, to enable Zipkin, one needs to edit `master/src/Makevars`, `master/src/worker/Makefile` and `master/src/executor/Makefile`. Take a look and see if that's ok.

**Comment by pratikdhandharia** [comment]
Hi @jorgemarsal , quick question, will the changes as a part of this pull request handle installing distributedR in R environment directory instead of installing it in /opt/{path..} when installed using make install command?

**Comment by jorgemarsal** [comment]
@pratikdhandharia Yes. No need to run `make install`. `R CMD INSTALL master` is enough.
The install location can be found from R using `system.file(package='distributedR')`

**Comment by pratikdhandharia** [comment]
@jorgemarsal , So do we need the scripts inside bin folder? Or should we get rid of those?

**Comment by jorgemarsal** [comment]
@pratikdhandharia Just leave them there for now.

**Comment by pratikdhandharia** [comment]
@jorgemarsal The reason I had asked, is because in the makefile the targets install and uninstall is still present. So if by mistake the user tries to use them, it will install distributedR in /opt folder. I feel, if we are making changes to let DistributedR install as a R-package, we should get rid of the install and uninstall target also and the corresponding scripts that it invokes unless there we want to support installtion using those targets. Apart from this I have no other comments for the PR.

**Comment by shreya2k7** [comment]
I tried this again.

Still getting build issues:

**Comment by shreya2k7** [comment]
Hi Jorge,

Tried again:
1. I still cant find info about Makefiles and how to do a clean build in the 1st comment you mentioned(the comment when you started this pull request). I wonder if I am looking at the right place.

2.You are right, those object files were from my old build.

3. I still see some build issues. Matrix_helper seems to depend on distributedR and vice-versa. Hence, DR and matrix_helper installation fails complaining they didnt find the other one.
Executor should be a dependency for DistributedR because it contains update() fn def. It should not be necessary to add matrix_helper as dependency for distributedR package. 
It works when matrix_helper is removed as dependency from distributedR package and the sequence of build is : 
R CMD INSTALL executor/
R CMD INSTALL distributedR/
R CMD INSTALL matrix_helper/
 
4. When I try to run unit tests, soon after I get a crash. Did you get a successful unit test run?

Thanks,
Shreya

**Comment by jorgemarsal** [comment]
Not sure what happened with my edited comment, it's not there anymore.

1. `cd platform/master/src`; make -f Makevars clean; make -f Makevars clean-third-party`
3. Removed the MatrixHelper dep from DR.
4. Works for me, unit tests pass. Can you try again with a perfectly clean build? Remove all *.o and *.so files. You can run  `cd platform/master/src`; make -f Makevars clean; make -f Makevars clean-third-party` and it'll do it

**Comment by jorgemarsal** [comment]
@pratikdhandharia Fixed the segault you saw. Can you try again?

**Comment by shreya2k7** [comment]
Hi Jorge,

1. The unit tests do not crash now in the same setup I tried with yesterday. Seems to be fixed with your segfault fix yesterday. There are 2 failures though, in which it cannot find the some c++ fns from matrix helper package. I have updated DISTR-917 to fix them.

2. The third-party cleanup doesnt seem to clear the whole third_party folder, for examples even after the cleanup commands are run for boost, he generated libraries in boost_1_50/ are still there etc. Currently when we do distclean, it removes everything, this ensures that we are doing a clean build and there are no traces left anywhere. Possible to fix it? Also, it seems we now need sudo to run the cleanup commands because we are using sudo for installation (otherwise get permission denied error).

3. Make target to cleanup Executor package in executor/src/Makevars is missing.

4. Can you also make high level make targets in top level 'Makefile' to build DR which has commands to install (containing R CMD INSTALL commands in right order), clean and distclean targets. It is just for convenience for us and as well as other people working with DR in github. 

Otherwise, it looks good to me.

**Comment by pratikdhandharia** [comment]
Hi @jorgemarsal , I tested the updated branch and I am not facing the seg-fault issue anymore. 

Regarding the unit test failure that Shreya mentioned in the previous comment, those should be fixed with pull request I created for removal of matrix helper package.

**Comment by jorgemarsal** [comment]
@shreya2k7 
2. We do not delete the whole folders but we run clean on them so all object files and shared libraries are removed.
3. The `executor` package only has source files under `src/` so no need to create a custom `clean` target. If you want to recompile everything you can run `R CMD INSTALL executor --preclean`
4. Done.

I'll merge this PR today.

**Comment by pratikdhandharia** [comment]
@jorgemarsal , just a quick question, should we merge the other pull-request for removal of matrix helper package in this branch first or we should merge it with master later after you merge your changes?

**Pull request merged**
